# Generated by Django 5.2.4 on 2025-07-25 08:00

import linebot_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebot_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closetitem',
            name='image',
            field=models.ImageField(upload_to=linebot_app.models.user_directory_path),
        ),
    ]
