# Generated by Django 5.2.4 on 2025-07-26 02:42

import linebot_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebot_app', '0002_alter_closetitem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MimicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('category', models.CharField(blank=True, max_length=32, null=True)),
                ('image', models.ImageField(upload_to=linebot_app.models.user_directory_mimic_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='closetitem',
            name='category',
        ),
    ]
