# Generated by Django 5.2.4 on 2025-07-26 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebot_app', '0003_mimicitem_remove_closetitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mimicitem',
            name='category',
        ),
        migrations.AddField(
            model_name='closetitem',
            name='category',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
