# Generated by Django 5.2.4 on 2025-07-30 04:57

import linebot_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebot_app', '0004_remove_mimicitem_category_closetitem_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='MimicBackendItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=64)),
                ('original_filename', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=linebot_app.models.backend_upload_path)),
                ('json_file', models.FileField(upload_to=linebot_app.models.backend_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
