# Generated by Django 5.2.4 on 2025-07-30 05:02

import linebot_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebot_app', '0005_mimicbackenditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mimicbackenditem',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to=linebot_app.models.backend_upload_path),
        ),
    ]
