# Generated by Django 5.2.4 on 2025-07-30 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebot_app', '0006_alter_mimicbackenditem_json_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='closetitem',
            name='backend_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mimic_items', to='linebot_app.mimicbackenditem'),
        ),
        migrations.AddField(
            model_name='mimicitem',
            name='backend_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
