# Generated by Django 5.2.4 on 2025-07-30 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linebot_app', '0008_remove_mimicbackenditem_json_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mimicbackenditem',
            name='original_filename',
        ),
    ]
