# Generated by Django 5.2.4 on 2025-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebot_app', '0009_remove_mimicbackenditem_original_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimicbackenditem',
            name='order_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
