# Generated by Django 5.2.4 on 2025-07-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linebot_app', '0011_remove_mimicbackenditem_order_filename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mimicbackenditem',
            name='serial_number',
        ),
    ]
