"""
Django settings for DjangoBlog project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-yzc6%!o+^0=+!*)20y&@iq%f%=&jr82!7pt4&d-!r0c(s6cqh6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "outfit",
    'linebot_app',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "APP.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates'],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
            "libraries": {
                "markdown_tag": "libraries.filter.markdown_filter",
            }
        },
    },
]



WSGI_APPLICATION = "APP.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "zh-hant"

TIME_ZONE = "Asia/Taipei"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "public/assets"
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

#定義只能到這裡存取資料夾，不給外來人存取
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


MEDIA_URL = '/media/'  # 用戶在瀏覽器中訪問上傳檔案時所用的 網址前綴
MEDIA_ROOT = BASE_DIR / 'media'

# BASE_URL = 'https://brianoxox.learnai2025.com'
# MEDIA_ROOT = '/home/babomomo26/AIOutfit/media/closet'  GCP實體照片存放位置

MEDIA_ROOT_CLOSET = os.path.join(BASE_DIR, 'media/closet')
MEDIA_CLOSET_PARTIAL_PATH = 'media/closet'

LIFF_CLOSET_ID = '2007855702-DxNEP27j'
LIFF_MIMIC_ID = '2007855702-rRq70YdD'
# LIFF_RECOMMEND_ID = '2007741127-V0Y2QDd2'

LINE_CHANNEL_ACCESS_TOKEN = '9LwvE0XoM3mBv1MyKeSDHOdsA9rJOS40yGQwlDEkHcWvaRTSrFJKcks9gZtX8COIRfpmgLRVR089euOmZskd0bSKhpQW8FJdQHPZKhjvr7MHes3v9T+anhSJMZPKgL8G1V3U4oFnS9CnNDyMkzNVqAdB04t89/1O/w1cDnyilFU='
LINE_CHANNEL_SECRET = 'b158389ed58d4f5699a08eb4b92ec37f' 


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,  # 保留原本的 loggers
    'formatters': {
        'verbose': {
            'format': '{asctime} [{levelname}] {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'ERROR',  # 只記錄 ERROR 等級以上
            'class': 'logging.FileHandler',
            'filename': os.path.join(BASE_DIR, 'logs', 'error.log'),  # logs 目錄
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['file'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}