# Generated by Django 5.2.4 on 2025-07-30 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linebot_app', '0007_closetitem_backend_item_mimicitem_backend_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mimicbackenditem',
            name='json_file',
        ),
    ]
