# Generated by Django 5.2.4 on 2025-07-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linebot_app', '0010_mimicbackenditem_order_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mimicbackenditem',
            name='order_filename',
        ),
        migrations.AddField(
            model_name='mimicbackenditem',
            name='serial_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
